### ISSUE TITLE
No module named 'htmd.molecule.voxeldescriptors'

### ISSUE THREAD

**Issue by Code-Temp** [BenevolentAI/DeeplyTough#22]
Hi,
I encountered an error when running your code: 

      Traceback (most recent call last):
        File "/data/zhangjunyi/DeeplyTough/deeplytough/scripts/toughm1_benchmark.py", line 6, in <module>
          from datasets import ToughM1
        File "/data/zhangjunyi/DeeplyTough/deeplytough/datasets/__init__.py", line 1, in <module>
          from .toughm1 import ToughM1
        File "/data/zhangjunyi/DeeplyTough/deeplytough/datasets/toughm1.py", line 16, in <module>
          from misc.utils import htmd_featurizer, voc_ap, RcsbPdbClusters, pdb_check_obsolete
        File "/data/zhangjunyi/DeeplyTough/deeplytough/misc/utils.py", line 10, in <module>
          import htmd.molecule.voxeldescriptors as htmdvox
      ModuleNotFoundError: No module named 'htmd.molecule.voxeldescriptors'

I have installed the **htmd version '1.27.0'**, and I think this might be an issue with the htmd version. May I ask which version of htmd you are using?

**Comment by JoshuaMeyers** [comment]
Hey, thanks for your interest in our code. The version needed is specified in the dockerfile provided: https://github.com/BenevolentAI/DeeplyTough/blob/7536c5bb7d4e1e7e5d4f6cfacd1a437db03596e9/Dockerfile#L47

I recommend you use the dockerfile, or the prebuilt image on dockerhub because these versions are now stale and tricky to build.
