### ISSUE TITLE
RuntimeError for custom_evaluation.py

### ISSUE THREAD

**Issue by RobinPoelmans** [BenevolentAI/DeeplyTough#23]
Hello,

When I try to run custom_evaluation.py on the example custom pairs, I get the following error:

Traceback (most recent call last):
  File "deeplytough/scripts/custom_evaluation.py", line 69, in <module>
    main()
  File "deeplytough/scripts/custom_evaluation.py", line 41, in main
    entries = matcher.precompute_descriptors(entries)
  File "/data/applic/DeeplyTough/deeplytough/matchers/deeply_tough.py", line 46, in precompute_descriptors
    feats = load_and_precompute_point_feats(self.model, self.args, pdb_list, point_list, self.device, self.nworkers, self.batch_size)
  File "/data/applic/DeeplyTough/deeplytough/engine/predictor.py", line 45, in load_and_precompute_point_feats
    outputs = model(inputs)
  File "/data/miniconda3/envs/deeplytough/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/applic/DeeplyTough/deeplytough/engine/models.py", line 95, in forward
    inputs = module(inputs)
  File "/data/miniconda3/envs/deeplytough/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/miniconda3/envs/deeplytough/lib/python3.6/site-packages/se3cnn-0.0.0-py3.6.egg/se3cnn/blocks/gated_block.py", line 154, in forward
  File "/data/miniconda3/envs/deeplytough/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/miniconda3/envs/deeplytough/lib/python3.6/site-packages/se3cnn-0.0.0-py3.6.egg/se3cnn/batchnorm.py", line 266, in forward
RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:258

I'm running DeeplyTough on an NVIDIA RTX A4500 GPU and did the setup of the conda environment exactly as described on this page. What could be the issue here?

**Comment by RobinPoelmans** [comment]
**UPDATE**

It's working after I upgraded torch using this command: 

pip install torch===1.7.1+cu110 torchvision===0.8.2+cu110 torchaudio===0.7.2 -f https://download.pytorch.org/whl/torch_stable.html -i https://pypi.douban.com/simple/

(Source: https://stackoverflow.com/questions/68164565/cublas-runtime-error-the-gpu-program-failed-to-execute-at-pytorch-aten-src-th)
