### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by adithigr** [BenevolentAI/DeeplyTough#27]
Please guide me with this error. Please!
WARNING:root:HTMD featurization file not found: C:UsersAdithiDownloadsbindDeeplyTough-masterDeeplyTough-master/processed/htmd/TOUGH-M1/TOUGH-M1_dataset/5jqwA/5jqwA.npz,corresponding pdb likely could not be parsed
WARNING:root:HTMD featurization file not found: C:UsersAdithiDownloadsbindDeeplyTough-masterDeeplyTough-master/processed/htmd/TOUGH-M1/TOUGH-M1_dataset/5jy1C/5jy1C.npz,corresponding pdb likely could not be parsed
WARNING:root:HTMD featurization file not found: C:UsersAdithiDownloadsbindDeeplyTough-masterDeeplyTough-master/processed/htmd/TOUGH-M1/TOUGH-M1_dataset/5k2xA/5k2xA.npz,corresponding pdb likely could not be parsed
WARNING:root:HTMD featurization file not found: C:UsersAdithiDownloadsbindDeeplyTough-masterDeeplyTough-master/processed/htmd/TOUGH-M1/TOUGH-M1_dataset/5nulA/5nulA.npz,corresponding pdb likely could not be parsed
WARNING:root:HTMD featurization file not found: C:UsersAdithiDownloadsbindDeeplyTough-masterDeeplyTough-master/processed/htmd/TOUGH-M1/TOUGH-M1_dataset/6a3hA/6a3hA.npz,corresponding pdb likely could not be parsed
WARNING:root:HTMD featurization file not found: C:UsersAdithiDownloadsbindDeeplyTough-masterDeeplyTough-master/processed/htmd/TOUGH-M1/TOUGH-M1_dataset/6gsyB/6gsyB.npz,corresponding pdb likely could not be parsed
WARNING:root:HTMD featurization file not found: C:UsersAdithiDownloadsbindDeeplyTough-masterDeeplyTough-master/processed/htmd/TOUGH-M1/TOUGH-M1_dataset/7aatA/7aatA.npz,corresponding pdb likely could not be parsed
WARNING:root:HTMD featurization file not found: C:UsersAdithiDownloadsbindDeeplyTough-masterDeeplyTough-master/processed/htmd/TOUGH-M1/TOUGH-M1_dataset/7acnA/7acnA.npz,corresponding pdb likely could not be parsed
WARNING:root:HTMD featurization file not found: C:UsersAdithiDownloadsbindDeeplyTough-masterDeeplyTough-master/processed/htmd/TOUGH-M1/TOUGH-M1_dataset/7stdB/7stdB.npz,corresponding pdb likely could not be parsed
WARNING:root:HTMD featurization file not found: C:UsersAdithiDownloadsbindDeeplyTough-masterDeeplyTough-master/processed/htmd/TOUGH-M1/TOUGH-M1_dataset/9abpA/9abpA.npz,corresponding pdb likely could not be parsed
Traceback (most recent call last):
  File "/mnt/c/Users/Adithi/Downloads/bind/DeeplyTough-master/DeeplyTough-master/deeplytough/scripts/train.py", line 311, in <module>
    main()
  File "/mnt/c/Users/Adithi/Downloads/bind/DeeplyTough-master/DeeplyTough-master/deeplytough/scripts/train.py", line 95, in main
    exclude_Vertex_from_train=args.db_exclude_vertex, exclude_Prospeccts_from_train=args.db_exclude_prospeccts
  File "/mnt/c/Users/Adithi/Downloads/bind/DeeplyTough-master/DeeplyTough-master/deeplytough/engine/datasets.py", line 319, in create_tough_dataset
    augm_decoy_prob=args.augm_decoy_prob, db_pairs_limit=-args.db_size_limit)
  File "/mnt/c/Users/Adithi/Downloads/bind/DeeplyTough-master/DeeplyTough-master/deeplytough/engine/datasets.py", line 125, in __init__
    super().__init__(pdb_list, box_size, augm_rot, augm_mirror_prob)
  File "/mnt/c/Users/Adithi/Downloads/bind/DeeplyTough-master/DeeplyTough-master/deeplytough/engine/datasets.py", line 46, in __init__
    assert len(self.pdb_list) > 0, f'No HTMD could be found but {len(pdb_list)}' \
AssertionError: No HTMD could be found but 6042PDB files were given, please call preprocess_once() on the dataset

**Comment by JoshuaMeyers** [comment]
It appears you haven't installed HTMD correctly, this dependency is highly out of date.

If you would truly like to use deeplytough, I would suggest starting from our image on Dockerhub, or building the docker image yourself since this repo has a few stale dependencies now which can be a bit fiddly to install (docker pull joshuameyers/deeplytough)

**Comment by adithigr** [comment]
Thank you for your input. Do you think there are any other tools like DeeplyTough currently? We are trying to figure it out, but all the tools seemed to be outdated.

**Comment by JoshuaMeyers** [comment]
Yep good point, I'm not working in this realm at the moment but I'd say the masif suite would be a step in the right direction 👍
